name: Build and publish image

on:
  schedule:
    # every Sunday (so it's stable through the week)
    - cron: '0 0 * * SUN'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # The actions/docker repository has disappeared, but we should be able to use the
      # docker command available directly in the virtual environment.
      - name: build and publish
        run: |
          docker login --username sthopeless --password ${{ secrets.DOCKER_PASSWORD }}
          docker build --tag sthopeless/ps2mqtt:latest .
          docker push sthopeless/ps2mqtt:latest
